//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 208.149102 on Stable branch
// Generated with ALiVE version 1.15.0.2112041
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class B_LivionianStalkersArmyArmy {
        displayName = "Livonia STALKER : Livonia Army";
        side = 1;
        flag = "\a3\UI_F_Enoch\Data\CfgMarkers\Livonia_CA.paa";
        icon = "\a3\UI_F_Enoch\Data\CfgMarkers\Livonia_CA.paa";
        priority = 0;
    };
};

//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 208.149102 on Stable branch
// Generated with ALiVE version 1.15.0.2112041
//////////////////////////////////////////////////////////////////////////////////


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class B_G_Survivor_F;
    class B_G_Survivor_F_OCimport_01 : B_G_Survivor_F { scope = 0; class EventHandlers; };
    class B_G_Survivor_F_OCimport_02 : B_G_Survivor_F_OCimport_01 { class EventHandlers; };


    class B_Livionian_Stalkers_ArmyArmy_Unarmed_01 : B_G_Survivor_F_OCimport_02 {
        author = "VaD_3r";
        scope = 2;
        scopeCurator = 2;
        displayName = "Unarmed";
        side = 1;
        faction = "b_livionianstalkersarmyarmy";

        identityTypes[] = {"Head_Euro","LanguageRUS","G_GUERIL_default"};

        uniformClass = "rhsgref_uniform_ttsko_forest";

        linkedItems[] = {"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"rhsgref_uniform_ttsko_forest",{}},{},{},"","",{},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'Spetsnaz223rdDetachment'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "Spetsnaz223rdDetachment";

    };

    class B_Livionian_Stalkers_ArmyArmy_Team_Leader_01 : B_Livionian_Stalkers_ArmyArmy_Unarmed_01 {
        author = "VaD_3r";
        scope = 2;
        scopeCurator = 2;
        displayName = "Team Leader";
        side = 1;
        faction = "b_livionianstalkersarmyarmy";

        identityTypes[] = {"Head_Euro","LanguageRUS","G_GUERIL_default"};

        uniformClass = "rhsgref_uniform_ttsko_forest";

        linkedItems[] = {"rhs_6b23_6sh116_mixed","rhs_6b26_green","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","rhs_1PN138"};
        respawnlinkedItems[] = {"rhs_6b23_6sh116_mixed","rhs_6b26_green","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","rhs_1PN138"};

        weapons[] = {"rhs_weap_ak103_npz","rhsusf_weap_glock17g4","Binocular"};
        respawnWeapons[] = {"rhs_weap_ak103_npz","rhsusf_weap_glock17g4","Binocular"};

        magazines[] = {"rhs_30Rnd_762x39mm_polymer","rhsusf_mag_17Rnd_9x19_JHP","rhs_30Rnd_762x39mm_polymer","rhsusf_mag_17Rnd_9x19_JHP"};
        respawnMagazines[] = {"rhs_30Rnd_762x39mm_polymer","rhsusf_mag_17Rnd_9x19_JHP","rhs_30Rnd_762x39mm_polymer","rhsusf_mag_17Rnd_9x19_JHP"};

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_ak103_npz","hlc_muzzle_snds_ArsenalComp","","rhsusf_acc_ACOG3_USMC",{"rhs_30Rnd_762x39mm_polymer",30},{},""},{},{"rhsusf_weap_glock17g4","","","",{"rhsusf_mag_17Rnd_9x19_JHP",17},{},""},{"rhsgref_uniform_ttsko_forest",{{"FirstAidKit",3},{"rhsusf_mag_17Rnd_9x19_JHP",2,17}}},{"rhs_6b23_6sh116_mixed",{{"rhs_30Rnd_762x39mm_polymer",10,30}}},{},"rhs_6b26_green","rhs_balaclava",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","rhs_1PN138"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'Spetsnaz223rdDetachment'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "Spetsnaz223rdDetachment";

    };

    class B_Livionian_Stalkers_ArmyArmy_Squad_Leader_01 : B_Livionian_Stalkers_ArmyArmy_Unarmed_01 {
        author = "VaD_3r";
        scope = 2;
        scopeCurator = 2;
        displayName = "Squad Leader";
        side = 1;
        faction = "b_livionianstalkersarmyarmy";

        identityTypes[] = {"Head_Euro","LanguageRUS","G_GUERIL_default"};

        uniformClass = "rhsgref_uniform_ttsko_forest";

        linkedItems[] = {"rhsgref_6b23_ttsko_digi_rifleman","rhs_6b26_green","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","rhs_1PN138"};
        respawnlinkedItems[] = {"rhsgref_6b23_ttsko_digi_rifleman","rhs_6b26_green","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","rhs_1PN138"};

        weapons[] = {"rhs_weap_ak74m","Binocular"};
        respawnWeapons[] = {"rhs_weap_ak74m","Binocular"};

        magazines[] = {"rhs_30Rnd_545x39_7N10_AK","rhs_30Rnd_545x39_7N10_AK"};
        respawnMagazines[] = {"rhs_30Rnd_545x39_7N10_AK","rhs_30Rnd_545x39_7N10_AK"};

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_ak74m","rhs_acc_dtk2","","rhs_acc_1p78",{"rhs_30Rnd_545x39_7N10_AK",30},{},""},{},{},{"rhsgref_uniform_ttsko_forest",{{"FirstAidKit",3},{"rhs_30Rnd_545x39_7N10_AK",1,30}}},{"rhsgref_6b23_ttsko_digi_rifleman",{{"rhs_30Rnd_545x39_7N10_AK",10,30}}},{},"rhs_6b26_green","",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","rhs_1PN138"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'Spetsnaz223rdDetachment'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "Spetsnaz223rdDetachment";

    };

    class B_Livionian_Stalkers_ArmyArmy_Rifleman_01 : B_Livionian_Stalkers_ArmyArmy_Unarmed_01 {
        author = "VaD_3r";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman";
        side = 1;
        faction = "b_livionianstalkersarmyarmy";

        identityTypes[] = {"Head_Euro","LanguageRUS","G_GUERIL_default"};

        uniformClass = "rhsgref_uniform_ttsko_forest";

        linkedItems[] = {"rhs_6b23_digi_rifleman","rhs_6b7_1m_emr","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","rhs_1PN138"};
        respawnlinkedItems[] = {"rhs_6b23_digi_rifleman","rhs_6b7_1m_emr","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","rhs_1PN138"};

        weapons[] = {"rhs_weap_ak74n","Binocular"};
        respawnWeapons[] = {"rhs_weap_ak74n","Binocular"};

        magazines[] = {"rhs_30Rnd_545x39_7N6M_AK","rhs_30Rnd_545x39_7N6M_AK"};
        respawnMagazines[] = {"rhs_30Rnd_545x39_7N6M_AK","rhs_30Rnd_545x39_7N6M_AK"};

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_ak74n","rhs_acc_dtk1983","","rhs_acc_1p63",{"rhs_30Rnd_545x39_7N6M_AK",30},{},""},{},{},{"rhsgref_uniform_ttsko_forest",{{"FirstAidKit",3},{"rhs_mag_rgn",2,1}}},{"rhs_6b23_digi_rifleman",{{"rhs_30Rnd_545x39_7N6M_AK",8,30},{"rhs_mag_rgo",1,1}}},{},"rhs_6b7_1m_emr","G_Shades_Black",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","rhs_1PN138"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'Spetsnaz223rdDetachment'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "Spetsnaz223rdDetachment";

    };

    class B_Livionian_Stalkers_ArmyArmy_Rifleman_AT_01 : B_Livionian_Stalkers_ArmyArmy_Unarmed_01 {
        author = "VaD_3r";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman (AT)";
        side = 1;
        faction = "b_livionianstalkersarmyarmy";

        identityTypes[] = {"Head_Euro","LanguageRUS","G_GUERIL_default"};

        uniformClass = "rhsgref_uniform_ttsko_forest";

        linkedItems[] = {"rhs_6b2_lifchik","rhs_6b7_1m_olive","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhs_6b2_lifchik","rhs_6b7_1m_olive","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_akms","rhs_weap_rpg7","Binocular"};
        respawnWeapons[] = {"rhs_weap_akms","rhs_weap_rpg7","Binocular"};

        magazines[] = {"rhs_30Rnd_762x39mm_bakelite","rhs_rpg7_PG7VL_mag","rhs_30Rnd_762x39mm_bakelite"};
        respawnMagazines[] = {"rhs_30Rnd_762x39mm_bakelite","rhs_rpg7_PG7VL_mag","rhs_30Rnd_762x39mm_bakelite"};

        backpack = "rhs_rpg_6b2";

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_akms","rhs_acc_dtkakm","","",{"rhs_30Rnd_762x39mm_bakelite",30},{},""},{"rhs_weap_rpg7","","","",{"rhs_rpg7_PG7VL_mag",1},{},""},{},{"rhsgref_uniform_ttsko_forest",{{"FirstAidKit",2},{"rhs_30Rnd_762x39mm_bakelite",2,30}}},{"rhs_6b2_lifchik",{{"rhs_30Rnd_762x39mm_bakelite",7,30}}},{"rhs_rpg_6b2",{{"rhs_rpg7_OG7V_mag",3,1},{"rhs_rpg7_PG7VL_mag",1,1},{"rhs_mag_rgn",1,1},{"rhs_mag_rgo",1,1}}},"rhs_6b7_1m_olive","",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'Spetsnaz223rdDetachment'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "Spetsnaz223rdDetachment";

    };

    class B_Livionian_Stalkers_ArmyArmy_Grenadier_01 : B_Livionian_Stalkers_ArmyArmy_Unarmed_01 {
        author = "VaD_3r";
        scope = 2;
        scopeCurator = 2;
        displayName = "Grenadier";
        side = 1;
        faction = "b_livionianstalkersarmyarmy";

        identityTypes[] = {"Head_Euro","LanguageRUS","G_GUERIL_default"};

        uniformClass = "rhsgref_uniform_ttsko_forest";

        linkedItems[] = {"rhs_6b23_digi_6sh92_vog","rhs_6b27m","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","rhs_1PN138"};
        respawnlinkedItems[] = {"rhs_6b23_digi_6sh92_vog","rhs_6b27m","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","rhs_1PN138"};

        weapons[] = {"rhs_weap_aks74n_gp25","Binocular"};
        respawnWeapons[] = {"rhs_weap_aks74n_gp25","Binocular"};

        magazines[] = {"rhs_30Rnd_545x39_7N6M_AK","rhs_VOG25","rhs_30Rnd_545x39_7N6M_AK","rhs_VOG25"};
        respawnMagazines[] = {"rhs_30Rnd_545x39_7N6M_AK","rhs_VOG25","rhs_30Rnd_545x39_7N6M_AK","rhs_VOG25"};

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_aks74n_gp25","rhs_acc_dtk","","CUP_optic_ekp_8_02",{"rhs_30Rnd_545x39_7N6M_AK",30},{"rhs_VOG25",1},""},{},{},{"rhsgref_uniform_ttsko_forest",{{"rhs_30Rnd_545x39_7N6M_AK",3,30},{"rhs_VOG25",3,1}}},{"rhs_6b23_digi_6sh92_vog",{{"rhs_30Rnd_545x39_7N6M_AK",7,30},{"rhs_VOG25",8,1},{"hlc_GRD_White",2,1},{"hlc_GRD_blue",2,1},{"hlc_GRD_Red",1,1}}},{},"rhs_6b27m","",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","rhs_1PN138"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'Spetsnaz223rdDetachment'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "Spetsnaz223rdDetachment";

    };

    class B_Livionian_Stalkers_ArmyArmy_Specialist_01 : B_Livionian_Stalkers_ArmyArmy_Unarmed_01 {
        author = "VaD_3r";
        scope = 2;
        scopeCurator = 2;
        displayName = "Specialist";
        side = 1;
        faction = "b_livionianstalkersarmyarmy";

        identityTypes[] = {"Head_Euro","LanguageRUS","G_GUERIL_default"};

        uniformClass = "rhs_uniform_gorka_r_g_gloves";

        linkedItems[] = {"rhs_6b23_6sh116_mixed","H_HelmetHBK_headset_F","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","rhsusf_ANPVS_15"};
        respawnlinkedItems[] = {"rhs_6b23_6sh116_mixed","H_HelmetHBK_headset_F","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","rhsusf_ANPVS_15"};

        weapons[] = {"CUP_arifle_G3A3_ris","Binocular"};
        respawnWeapons[] = {"CUP_arifle_G3A3_ris","Binocular"};

        magazines[] = {"CUP_20Rnd_762x51_G3","CUP_20Rnd_762x51_G3"};
        respawnMagazines[] = {"CUP_20Rnd_762x51_G3","CUP_20Rnd_762x51_G3"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_G3A3_ris","rhsusf_acc_aac_scarh_silencer","rhsusf_acc_anpeq15side_bk","rhs_acc_ekp8_18",{"CUP_20Rnd_762x51_G3",20},{},"CUP_bipod_G3"},{},{},{"rhs_uniform_gorka_r_g_gloves",{{"rhs_mag_rgn",2,1},{"rhs_mag_rgo",2,1}}},{"rhs_6b23_6sh116_mixed",{{"CUP_20Rnd_762x51_G3",11,20}}},{},"H_HelmetHBK_headset_F","rhsusf_shemagh2_grn",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","rhsusf_ANPVS_15"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'Spetsnaz223rdDetachment'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "Spetsnaz223rdDetachment";

    };

    class B_Livionian_Stalkers_ArmyArmy_Machine_Gunner_01 : B_Livionian_Stalkers_ArmyArmy_Unarmed_01 {
        author = "VaD_3r";
        scope = 2;
        scopeCurator = 2;
        displayName = "Machine Gunner";
        side = 1;
        faction = "b_livionianstalkersarmyarmy";

        identityTypes[] = {"Head_Euro","LanguageRUS","G_GUERIL_default"};

        uniformClass = "rhsgref_uniform_ttsko_forest";

        linkedItems[] = {"rhs_6b13_Flora_6sh92","rhs_altyn_novisor","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","rhs_1PN138"};
        respawnlinkedItems[] = {"rhs_6b13_Flora_6sh92","rhs_altyn_novisor","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","rhs_1PN138"};

        weapons[] = {"rhs_weap_pkp","Binocular"};
        respawnWeapons[] = {"rhs_weap_pkp","Binocular"};

        magazines[] = {"rhs_100Rnd_762x54mmR","rhs_100Rnd_762x54mmR"};
        respawnMagazines[] = {"rhs_100Rnd_762x54mmR","rhs_100Rnd_762x54mmR"};

        backpack = "B_AssaultPack_dgtl";

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_pkp","","","rhs_acc_1p78",{"rhs_100Rnd_762x54mmR",100},{},""},{},{},{"rhsgref_uniform_ttsko_forest",{{"FirstAidKit",2}}},{"rhs_6b13_Flora_6sh92",{{"rhs_100Rnd_762x54mmR",1,100}}},{"B_AssaultPack_dgtl",{{"rhs_100Rnd_762x54mmR",2,100}}},"rhs_altyn_novisor","G_Balaclava_combat",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","rhs_1PN138"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'Spetsnaz223rdDetachment'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "Spetsnaz223rdDetachment";

    };

    class B_Livionian_Stalkers_ArmyArmy_Machine_Gunner_Assistant_01 : B_Livionian_Stalkers_ArmyArmy_Unarmed_01 {
        author = "VaD_3r";
        scope = 2;
        scopeCurator = 2;
        displayName = "Machine Gunner Assistant";
        side = 1;
        faction = "b_livionianstalkersarmyarmy";

        identityTypes[] = {"Head_Euro","LanguageRUS","G_GUERIL_default"};

        uniformClass = "rhsgref_uniform_ttsko_forest";

        linkedItems[] = {"rhs_6b13_Flora_6sh92","rhs_6b28_green_bala","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","rhs_1PN138"};
        respawnlinkedItems[] = {"rhs_6b13_Flora_6sh92","rhs_6b28_green_bala","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","rhs_1PN138"};

        weapons[] = {"rhs_weap_aks74un","Binocular"};
        respawnWeapons[] = {"rhs_weap_aks74un","Binocular"};

        magazines[] = {"rhs_30Rnd_545x39_7N6M_AK","rhs_30Rnd_545x39_7N6M_AK"};
        respawnMagazines[] = {"rhs_30Rnd_545x39_7N6M_AK","rhs_30Rnd_545x39_7N6M_AK"};

        backpack = "rhs_tortila_olive";

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_aks74un","rhs_acc_pgs64_74u","","hlc_optic_kobra",{"rhs_30Rnd_545x39_7N6M_AK",30},{},""},{},{},{"rhsgref_uniform_ttsko_forest",{{"FirstAidKit",1},{"rhs_30Rnd_545x39_7N6M_AK",3,30}}},{"rhs_6b13_Flora_6sh92",{{"rhs_30Rnd_545x39_7N6M_AK",6,30}}},{"rhs_tortila_olive",{{"rhs_100Rnd_762x54mmR",4,100}}},"rhs_6b28_green_bala","",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","rhs_1PN138"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'Spetsnaz223rdDetachment'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "Spetsnaz223rdDetachment";

    };

    class B_Livionian_Stalkers_ArmyArmy_Auto_Rifleman_01 : B_Livionian_Stalkers_ArmyArmy_Unarmed_01 {
        author = "VaD_3r";
        scope = 2;
        scopeCurator = 2;
        displayName = "Auto Rifleman";
        side = 1;
        faction = "b_livionianstalkersarmyarmy";

        identityTypes[] = {"Head_Euro","LanguageRUS","G_GUERIL_default"};

        uniformClass = "rhsgref_uniform_ttsko_forest";

        linkedItems[] = {"rhs_6b13_EMR_6sh92","rhssaf_bandana_oakleaf","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhs_6b13_EMR_6sh92","rhssaf_bandana_oakleaf","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_rpk74m_npz","Binocular"};
        respawnWeapons[] = {"rhs_weap_rpk74m_npz","Binocular"};

        magazines[] = {"rhs_45Rnd_545X39_7N6M_AK","rhs_45Rnd_545X39_7N6M_AK"};
        respawnMagazines[] = {"rhs_45Rnd_545X39_7N6M_AK","rhs_45Rnd_545X39_7N6M_AK"};

        backpack = "B_AssaultPack_dgtl";

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_rpk74m_npz","rhs_acc_dtkrpk","","rhsusf_acc_EOTECH",{"rhs_45Rnd_545X39_7N6M_AK",45},{},""},{},{},{"rhsgref_uniform_ttsko_forest",{{"rhs_45Rnd_545X39_7N6M_AK",2,45}}},{"rhs_6b13_EMR_6sh92",{{"rhs_45Rnd_545X39_7N6M_AK",7,45}}},{"B_AssaultPack_dgtl",{{"rhs_45Rnd_545X39_7N6M_AK",5,45}}},"rhssaf_bandana_oakleaf","G_Combat_Goggles_tna_F",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'Spetsnaz223rdDetachment'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "Spetsnaz223rdDetachment";

    };

    class B_Livionian_Stalkers_ArmyArmy_Sniper_01 : B_Livionian_Stalkers_ArmyArmy_Unarmed_01 {
        author = "VaD_3r";
        scope = 2;
        scopeCurator = 2;
        displayName = "Sniper";
        side = 1;
        faction = "b_livionianstalkersarmyarmy";

        identityTypes[] = {"Head_Euro","LanguageRUS","G_GUERIL_default"};

        uniformClass = "rhsgref_uniform_ttsko_forest";

        linkedItems[] = {"rhs_6b5_vsr","rhs_fieldcap","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles_OPFOR"};
        respawnlinkedItems[] = {"rhs_6b5_vsr","rhs_fieldcap","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles_OPFOR"};

        weapons[] = {"rhs_weap_svds_npz","rhsusf_weap_glock17g4","Binocular"};
        respawnWeapons[] = {"rhs_weap_svds_npz","rhsusf_weap_glock17g4","Binocular"};

        magazines[] = {"rhs_10Rnd_762x54mmR_7N1","rhsusf_mag_17Rnd_9x19_JHP","rhs_10Rnd_762x54mmR_7N1","rhsusf_mag_17Rnd_9x19_JHP"};
        respawnMagazines[] = {"rhs_10Rnd_762x54mmR_7N1","rhsusf_mag_17Rnd_9x19_JHP","rhs_10Rnd_762x54mmR_7N1","rhsusf_mag_17Rnd_9x19_JHP"};

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_svds_npz","rhs_acc_tgpv","","rhs_acc_dh520x56",{"rhs_10Rnd_762x54mmR_7N1",10},{},""},{},{"rhsusf_weap_glock17g4","","","",{"rhsusf_mag_17Rnd_9x19_JHP",17},{},""},{"rhsgref_uniform_ttsko_forest",{{"FirstAidKit",2},{"rhsusf_mag_17Rnd_9x19_JHP",4,17}}},{"rhs_6b5_vsr",{{"rhs_10Rnd_762x54mmR_7N1",15,10}}},{},"rhs_fieldcap","",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","NVGoggles_OPFOR"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'Spetsnaz223rdDetachment'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "Spetsnaz223rdDetachment";

    };

};

//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 208.149102 on Stable branch
// Generated with ALiVE version 1.15.0.2112041
//////////////////////////////////////////////////////////////////////////////////

class CfgGroups {
    class WEST {

        class B_LivionianStalkersArmyArmy {
            name = "Livonia STALKER : Livonia Army";

            class Infantry {
                name = "Infantry";

                class b_livionian_stalkers_armyarmy_infantry_team {
                    name = "Team";
                    side = 1;
                    faction = "b_livionianstalkersarmyarmy";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_Livionian_Stalkers_ArmyArmy_Team_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Livionian_Stalkers_ArmyArmy_Squad_Leader_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Livionian_Stalkers_ArmyArmy_Specialist_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Livionian_Stalkers_ArmyArmy_Grenadier_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Livionian_Stalkers_ArmyArmy_Rifleman_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Livionian_Stalkers_ArmyArmy_Rifleman_AT_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Livionian_Stalkers_ArmyArmy_Machine_Gunner_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Livionian_Stalkers_ArmyArmy_Machine_Gunner_Assistant_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Livionian_Stalkers_ArmyArmy_Auto_Rifleman_01";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Livionian_Stalkers_ArmyArmy_Sniper_01";
                    };
                };

                class b_livionian_stalkers_armyarmy_infantry_squad {
                    name = "Squad";
                    side = 1;
                    faction = "b_livionianstalkersarmyarmy";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_Livionian_Stalkers_ArmyArmy_Squad_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Livionian_Stalkers_ArmyArmy_Specialist_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Livionian_Stalkers_ArmyArmy_Grenadier_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Livionian_Stalkers_ArmyArmy_Sniper_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Livionian_Stalkers_ArmyArmy_Machine_Gunner_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Livionian_Stalkers_ArmyArmy_Machine_Gunner_Assistant_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Livionian_Stalkers_ArmyArmy_Auto_Rifleman_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Livionian_Stalkers_ArmyArmy_Rifleman_AT_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Livionian_Stalkers_ArmyArmy_Rifleman_01";
                    };
                };

                class b_livionian_stalkers_armyarmy_infantry_recon {
                    name = "Recon";
                    side = 1;
                    faction = "b_livionianstalkersarmyarmy";
                    icon = "\A3\ui_f\data\map\markers\nato\b_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_Livionian_Stalkers_ArmyArmy_Team_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Livionian_Stalkers_ArmyArmy_Specialist_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Livionian_Stalkers_ArmyArmy_Sniper_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Livionian_Stalkers_ArmyArmy_Auto_Rifleman_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Livionian_Stalkers_ArmyArmy_Rifleman_AT_01";
                    };
                };

                class b_livionian_stalkers_armyarmy_infantry_patrol {
                    name = "Patrol";
                    side = 1;
                    faction = "b_livionianstalkersarmyarmy";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_Livionian_Stalkers_ArmyArmy_Squad_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Livionian_Stalkers_ArmyArmy_Grenadier_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Livionian_Stalkers_ArmyArmy_Machine_Gunner_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Livionian_Stalkers_ArmyArmy_Rifleman_01";
                    };
                };

                class b_livionian_stalkers_armyarmy_infantry_special {
                    name = "Special";
                    side = 1;
                    faction = "b_livionianstalkersarmyarmy";
                    icon = "\A3\ui_f\data\map\markers\nato\b_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 1;
                        vehicle = "B_Livionian_Stalkers_ArmyArmy_Squad_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Livionian_Stalkers_ArmyArmy_Specialist_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Livionian_Stalkers_ArmyArmy_Grenadier_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Livionian_Stalkers_ArmyArmy_Sniper_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 1;
                        vehicle = "B_Livionian_Stalkers_ArmyArmy_Rifleman_AT_01";
                    };
                };

            };

            class SpecOps {
                name = "SpecOps";

            };

            class Motorized {
                name = "Motorized";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support";

            };

            class Mechanized {
                name = "Mechanized";

            };

            class Armored {
                name = "Armored";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};