//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 208.149102 on Stable branch
// Generated with ALiVE version 1.15.0.2112041
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class I_25ThHourArmy {
        displayName = "Livonia STALKER : 25th Hour";
        side = 2;
        flag = "\A3\ui_f\data\map\markers\flags\FIA_ca.paa";
        icon = "\A3\ui_f\data\map\markers\flags\FIA_ca.paa";
        priority = 0;
    };
};

//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 208.149102 on Stable branch
// Generated with ALiVE version 1.15.0.2112041
//////////////////////////////////////////////////////////////////////////////////


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class B_Soldier_F;
    class B_Soldier_F_OCimport_01 : B_Soldier_F { scope = 0; class EventHandlers; };
    class B_Soldier_F_OCimport_02 : B_Soldier_F_OCimport_01 { class EventHandlers; };


    class I_25Th_HourArmy_Unarmed_01 : B_Soldier_F_OCimport_02 {
        author = "VaD_3r";
        scope = 2;
        scopeCurator = 2;
        displayName = "Unarmed";
        side = 2;
        faction = "I_25ThHourArmy";

        identityTypes[] = {"Head_Euro","LanguageENG_F","G_NATO_default"};

        uniformClass = "U_C_CBRN_Suit_01_Blue_F";

        linkedItems[] = {"ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"U_C_CBRN_Suit_01_Blue_F",{}},{},{},"","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_25Th_HourArmy_Zealot_01 : I_25Th_HourArmy_Unarmed_01 {
        author = "VaD_3r";
        scope = 2;
        scopeCurator = 2;
        displayName = "Zealot";
        side = 2;
        faction = "I_25ThHourArmy";

        identityTypes[] = {"Head_Euro","LanguageENG_F","G_NATO_default"};

        uniformClass = "U_C_CBRN_Suit_01_Blue_F";

        linkedItems[] = {"rhsgref_6b23_ttsko_digi_rifleman","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhsgref_6b23_ttsko_digi_rifleman","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_ak103","Binocular"};
        respawnWeapons[] = {"rhs_weap_ak103","Binocular"};

        magazines[] = {"rhs_30Rnd_762x39mm_polymer","rhs_30Rnd_762x39mm_polymer"};
        respawnMagazines[] = {"rhs_30Rnd_762x39mm_polymer","rhs_30Rnd_762x39mm_polymer"};

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_ak103","rhs_acc_dtk","","CUP_optic_Kobra",{"rhs_30Rnd_762x39mm_polymer",30},{},""},{},{},{"U_C_CBRN_Suit_01_Blue_F",{{"FirstAidKit",3}}},{"rhsgref_6b23_ttsko_digi_rifleman",{{"rhs_30Rnd_762x39mm_polymer",8,30}}},{},"","rhsusf_shemagh2_white",{"Binocular","","","",{},{},""},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_25Th_HourArmy_Priest_01 : I_25Th_HourArmy_Unarmed_01 {
        author = "VaD_3r";
        scope = 2;
        scopeCurator = 2;
        displayName = "Priest";
        side = 2;
        faction = "I_25ThHourArmy";

        identityTypes[] = {"Head_Euro","LanguageENG_F","G_NATO_default"};

        uniformClass = "U_C_CBRN_Suit_01_Blue_F";

        linkedItems[] = {"rhs_6b23_6sh116","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhs_6b23_6sh116","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_pm63"};
        respawnWeapons[] = {"rhs_weap_pm63"};

        magazines[] = {"rhs_30Rnd_762x39mm","rhs_30Rnd_762x39mm"};
        respawnMagazines[] = {"rhs_30Rnd_762x39mm","rhs_30Rnd_762x39mm"};

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_pm63","rhs_acc_dtkakm","","",{"rhs_30Rnd_762x39mm",30},{},""},{},{},{"U_C_CBRN_Suit_01_Blue_F",{{"FirstAidKit",3}}},{"rhs_6b23_6sh116",{{"rhs_30Rnd_762x39mm",10,30}}},{},"","rhsusf_shemagh2_white",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_25Th_HourArmy_Bishop_01 : I_25Th_HourArmy_Unarmed_01 {
        author = "VaD_3r";
        scope = 2;
        scopeCurator = 2;
        displayName = "Bishop";
        side = 2;
        faction = "I_25ThHourArmy";

        identityTypes[] = {"Head_Euro","LanguageENG_F","G_NATO_default"};

        uniformClass = "U_C_CBRN_Suit_01_Blue_F";

        linkedItems[] = {"rhsgref_6b23_khaki_rifleman","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhsgref_6b23_khaki_rifleman","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_ak74_3"};
        respawnWeapons[] = {"rhs_weap_ak74_3"};

        magazines[] = {"rhs_30Rnd_545x39_7N6_green_AK","rhs_30Rnd_545x39_7N6_green_AK"};
        respawnMagazines[] = {"rhs_30Rnd_545x39_7N6_green_AK","rhs_30Rnd_545x39_7N6_green_AK"};

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_ak74_3","rhs_acc_dtk","","",{"rhs_30Rnd_545x39_7N6_green_AK",30},{},""},{},{},{"U_C_CBRN_Suit_01_Blue_F",{{"FirstAidKit",3}}},{"rhsgref_6b23_khaki_rifleman",{{"rhs_30Rnd_545x39_7N6_green_AK",10,30}}},{},"","rhsusf_shemagh2_white",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_25Th_HourArmy_Specialist_01 : I_25Th_HourArmy_Unarmed_01 {
        author = "VaD_3r";
        scope = 2;
        scopeCurator = 2;
        displayName = "Specialist";
        side = 2;
        faction = "I_25ThHourArmy";

        identityTypes[] = {"Head_Euro","LanguageENG_F","G_NATO_default"};

        uniformClass = "U_C_CBRN_Suit_01_Blue_F";

        linkedItems[] = {"ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_ak105","rhs_weap_rpg7"};
        respawnWeapons[] = {"rhs_weap_ak105","rhs_weap_rpg7"};

        magazines[] = {"rhs_30Rnd_545x39_7N10_AK","rhs_rpg7_PG7VL_mag","rhs_30Rnd_545x39_7N10_AK"};
        respawnMagazines[] = {"rhs_30Rnd_545x39_7N10_AK","rhs_rpg7_PG7VL_mag","rhs_30Rnd_545x39_7N10_AK"};

        backpack = "rhs_rpg_6b2";

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_ak105","rhs_acc_dtk1983","","",{"rhs_30Rnd_545x39_7N10_AK",30},{},""},{"rhs_weap_rpg7","","","",{"rhs_rpg7_PG7VL_mag",1},{},""},{},{"U_C_CBRN_Suit_01_Blue_F",{{"rhs_30Rnd_545x39_7N10_AK",3,30}}},{},{"rhs_rpg_6b2",{{"rhs_rpg7_OG7V_mag",2,1},{"rhs_30Rnd_545x39_7N10_AK",9,30}}},"","rhsusf_shemagh2_white",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_25Th_HourArmy_Auto_Rifleman_01 : I_25Th_HourArmy_Unarmed_01 {
        author = "VaD_3r";
        scope = 2;
        scopeCurator = 2;
        displayName = "Auto Rifleman";
        side = 2;
        faction = "I_25ThHourArmy";

        identityTypes[] = {"Head_Euro","LanguageENG_F","G_NATO_default"};

        uniformClass = "U_C_CBRN_Suit_01_Blue_F";

        linkedItems[] = {"rhsgref_6b23_ttsko_mountain_rifleman","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhsgref_6b23_ttsko_mountain_rifleman","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"CUP_arifle_G36A3","Binocular"};
        respawnWeapons[] = {"CUP_arifle_G36A3","Binocular"};

        magazines[] = {"CUP_30Rnd_556x45_G36","CUP_30Rnd_556x45_G36"};
        respawnMagazines[] = {"CUP_30Rnd_556x45_G36","CUP_30Rnd_556x45_G36"};

        backpack = "B_AssaultPack_blk";

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_G36A3","","","",{"CUP_30Rnd_556x45_G36",30},{},""},{},{},{"U_C_CBRN_Suit_01_Blue_F",{{"CUP_30Rnd_556x45_G36",3,30}}},{"rhsgref_6b23_ttsko_mountain_rifleman",{{"CUP_100Rnd_556x45_BetaCMag",4,100}}},{"B_AssaultPack_blk",{{"CUP_100Rnd_556x45_BetaCMag",3,100}}},"","rhsusf_shemagh2_white",{"Binocular","","","",{},{},""},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_25Th_HourArmy_Sniper_01 : I_25Th_HourArmy_Unarmed_01 {
        author = "VaD_3r";
        scope = 2;
        scopeCurator = 2;
        displayName = "Sniper";
        side = 2;
        faction = "I_25ThHourArmy";

        identityTypes[] = {"Head_Euro","LanguageENG_F","G_NATO_default"};

        uniformClass = "U_C_CBRN_Suit_01_Blue_F";

        linkedItems[] = {"rhs_6b2_SVD","ItemMap","ItemRadio","ItemCompass","ItemWatch","NVGoggles_OPFOR"};
        respawnlinkedItems[] = {"rhs_6b2_SVD","ItemMap","ItemRadio","ItemCompass","ItemWatch","NVGoggles_OPFOR"};

        weapons[] = {"hlc_rifle_FN3011Tactical_green","Binocular"};
        respawnWeapons[] = {"hlc_rifle_FN3011Tactical_green","Binocular"};

        magazines[] = {"hlc_10Rnd_762x51_B_fal","hlc_10Rnd_762x51_B_fal"};
        respawnMagazines[] = {"hlc_10Rnd_762x51_B_fal","hlc_10Rnd_762x51_B_fal"};

        backpack = "B_AssaultPack_blk";

        ALiVE_orbatCreator_loadout[] = {{"hlc_rifle_FN3011Tactical_green","rhsgref_sdn6_suppressor","","optic_SOS_khk_F",{"hlc_10Rnd_762x51_B_fal",10},{},""},{},{},{"U_C_CBRN_Suit_01_Blue_F",{{"hlc_10Rnd_762x51_B_fal",3,10}}},{"rhs_6b2_SVD",{{"hlc_10Rnd_762x51_B_fal",9,10}}},{"B_AssaultPack_blk",{{"hlc_50Rnd_762x51_B_fal",1,50}}},"","rhsusf_shemagh2_white",{"Binocular","","","",{},{},""},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch","NVGoggles_OPFOR"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_25Th_HourArmy_Rifleman_01 : I_25Th_HourArmy_Unarmed_01 {
        author = "VaD_3r";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman";
        side = 2;
        faction = "I_25ThHourArmy";

        identityTypes[] = {"Head_Euro","LanguageENG_F","G_NATO_default"};

        uniformClass = "U_C_CBRN_Suit_01_Blue_F";

        linkedItems[] = {"rhs_6b13_6sh92","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhs_6b13_6sh92","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_akm"};
        respawnWeapons[] = {"rhs_weap_akm"};

        magazines[] = {"rhs_30Rnd_762x39mm_bakelite","rhs_30Rnd_762x39mm_bakelite"};
        respawnMagazines[] = {"rhs_30Rnd_762x39mm_bakelite","rhs_30Rnd_762x39mm_bakelite"};

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_akm","rhs_acc_dtkakm","","",{"rhs_30Rnd_762x39mm_bakelite",30},{},""},{},{},{"U_C_CBRN_Suit_01_Blue_F",{{"FirstAidKit",3}}},{"rhs_6b13_6sh92",{{"rhs_30Rnd_762x39mm_bakelite",8,30}}},{},"","rhsusf_shemagh2_white",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class I_25Th_HourArmy_Missionary_01 : I_25Th_HourArmy_Unarmed_01 {
        author = "VaD_3r";
        scope = 2;
        scopeCurator = 2;
        displayName = "Missionary";
        side = 2;
        faction = "I_25ThHourArmy";

        identityTypes[] = {"Head_Euro","LanguageENG_F","G_NATO_default"};

        uniformClass = "U_C_FormalSuit_01_gray_F";

        linkedItems[] = {"H_Bandanna_gry","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"H_Bandanna_gry","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"U_C_FormalSuit_01_gray_F",{}},{},{},"H_Bandanna_gry","rhsusf_shemagh2_white",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

};

//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 208.149102 on Stable branch
// Generated with ALiVE version 1.15.0.2112041
//////////////////////////////////////////////////////////////////////////////////

class CfgGroups {
    class Indep {

        class I_25ThHourArmy {
            name = "Livonia STALKER : 25th Hour";

            class Infantry {
                name = "Infantry";

                class i_25th_hourarmy_infantry_team {
                    name = "Team";
                    side = 2;
                    faction = "I_25ThHourArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_25Th_HourArmy_Zealot_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_25Th_HourArmy_Priest_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_25Th_HourArmy_Bishop_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_25Th_HourArmy_Specialist_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_25Th_HourArmy_Sniper_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_25Th_HourArmy_Auto_Rifleman_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_25Th_HourArmy_Rifleman_01";
                    };
                };

                class i_25th_hourarmy_infantry_squad {
                    name = "Squad";
                    side = 2;
                    faction = "I_25ThHourArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_25Th_HourArmy_Priest_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_25Th_HourArmy_Bishop_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_25Th_HourArmy_Specialist_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_25Th_HourArmy_Sniper_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_25Th_HourArmy_Auto_Rifleman_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_25Th_HourArmy_Rifleman_01";
                    };
                };

                class i_25th_hourarmy_infantry_recon {
                    name = "Recon";
                    side = 2;
                    faction = "I_25ThHourArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\n_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_25Th_HourArmy_Zealot_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_25Th_HourArmy_Specialist_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_25Th_HourArmy_Sniper_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_25Th_HourArmy_Auto_Rifleman_01";
                    };
                };

                class i_25th_hourarmy_infantry_patrol {
                    name = "Patrol";
                    side = 2;
                    faction = "I_25ThHourArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_25Th_HourArmy_Bishop_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_25Th_HourArmy_Specialist_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_25Th_HourArmy_Sniper_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_25Th_HourArmy_Auto_Rifleman_01";
                    };
                };

                class i_25th_hourarmy_infantry_special {
                    name = "Special";
                    side = 2;
                    faction = "I_25ThHourArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_25Th_HourArmy_Zealot_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_25Th_HourArmy_Priest_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_25Th_HourArmy_Bishop_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_25Th_HourArmy_Specialist_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_25Th_HourArmy_Sniper_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_25Th_HourArmy_Auto_Rifleman_01";
                    };
                };

                class i_25th_hourarmy_infantry_missionary_group {
                    name = "Missionary Group";
                    side = 2;
                    faction = "I_25ThHourArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_25Th_HourArmy_Specialist_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_25Th_HourArmy_Auto_Rifleman_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_25Th_HourArmy_Rifleman_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_25Th_HourArmy_Missionary_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_25Th_HourArmy_Missionary_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_25Th_HourArmy_Missionary_01";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

            };

            class Motorized {
                name = "Motorized Infantry";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

            };

            class Armored {
                name = "Armor";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};