//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 208.149102 on Stable branch
// Generated with ALiVE version 1.15.0.2112041
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class O_LibertyArmy {
        displayName = "Livonia STALKER : Liberty";
        side = 0;
        flag = "\A3\ui_f\data\map\markers\flags\CSAT_ca.paa";
        icon = "\A3\ui_f\data\map\markers\flags\CSAT_ca.paa";
        priority = 0;
    };
};

//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 208.149102 on Stable branch
// Generated with ALiVE version 1.15.0.2112041
//////////////////////////////////////////////////////////////////////////////////


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class rhsgref_ins_rifleman_akm;
    class rhsgref_ins_rifleman_akm_OCimport_01 : rhsgref_ins_rifleman_akm { scope = 0; class EventHandlers; };
    class rhsgref_ins_rifleman_akm_OCimport_02 : rhsgref_ins_rifleman_akm_OCimport_01 { class EventHandlers; };


    class O_LibertyArmy_Unarmed_01 : rhsgref_ins_rifleman_akm_OCimport_02 {
        author = "VaD_3r";
        scope = 2;
        scopeCurator = 2;
        displayName = "Unarmed";
        side = 0;
        faction = "O_LibertyArmy";

        identityTypes[] = {"Head_Euro","LanguageRUS","rhs_scarf","G_CIVIL_male"};

        uniformClass = "rhs_uniform_FROG01_wd";

        linkedItems[] = {"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"Binocular"};
        respawnWeapons[] = {"Binocular"};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"rhs_uniform_FROG01_wd",{{"FirstAidKit",1},{"rhs_mag_rgd5",1,1}}},{},{},"","",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'CTRG'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "CTRG";

    };

    class O_LibertyArmy_Team_Leader_01 : O_LibertyArmy_Unarmed_01 {
        author = "VaD_3r";
        scope = 2;
        scopeCurator = 2;
        displayName = "Team Leader";
        side = 0;
        faction = "O_LibertyArmy";

        identityTypes[] = {"Head_Euro","LanguageRUS","rhs_scarf","G_CIVIL_male"};

        uniformClass = "rhs_uniform_FROG01_wd";

        linkedItems[] = {"rhsusf_spc_teamleader","rhsusf_opscore_mar_ut_pelt","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","rhsusf_ANPVS_14"};
        respawnlinkedItems[] = {"rhsusf_spc_teamleader","rhsusf_opscore_mar_ut_pelt","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","rhsusf_ANPVS_14"};

        weapons[] = {"rhs_weap_m4a1_carryhandle","Binocular"};
        respawnWeapons[] = {"rhs_weap_m4a1_carryhandle","Binocular"};

        magazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag","rhs_mag_30Rnd_556x45_M855A1_Stanag"};
        respawnMagazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag","rhs_mag_30Rnd_556x45_M855A1_Stanag"};

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_m4a1_carryhandle","","rhs_acc_2dpZenit_ris","rhs_acc_1p87",{"rhs_mag_30Rnd_556x45_M855A1_Stanag",30},{},"rhsusf_acc_grip2"},{},{},{"rhs_uniform_FROG01_wd",{{"FirstAidKit",2},{"rhs_mag_rgd5",1,1},{"rhs_mag_m67",1,1}}},{"rhsusf_spc_teamleader",{{"rhs_mag_30Rnd_556x45_M855A1_Stanag",11,30},{"rhs_mag_m67",2,1}}},{},"rhsusf_opscore_mar_ut_pelt","rhsusf_shemagh2_gogg_tan",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","rhsusf_ANPVS_14"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'CTRG'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "CTRG";

    };

    class O_LibertyArmy_Squad_Leader_01 : O_LibertyArmy_Unarmed_01 {
        author = "VaD_3r";
        scope = 2;
        scopeCurator = 2;
        displayName = "Squad Leader";
        side = 0;
        faction = "O_LibertyArmy";

        identityTypes[] = {"Head_Euro","LanguageRUS","rhs_scarf","G_CIVIL_male"};

        uniformClass = "rhs_uniform_FROG01_wd";

        linkedItems[] = {"rhs_6b3_AK_3","rhsusf_ach_bare_headset","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","rhs_1PN138"};
        respawnlinkedItems[] = {"rhs_6b3_AK_3","rhsusf_ach_bare_headset","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","rhs_1PN138"};

        weapons[] = {"rhs_weap_m4","Binocular"};
        respawnWeapons[] = {"rhs_weap_m4","Binocular"};

        magazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag","rhs_mag_30Rnd_556x45_M855A1_Stanag"};
        respawnMagazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag","rhs_mag_30Rnd_556x45_M855A1_Stanag"};

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_m4","","","rhsusf_acc_ELCAN",{"rhs_mag_30Rnd_556x45_M855A1_Stanag",30},{},"rhs_acc_grip_rk6"},{},{},{"rhs_uniform_FROG01_wd",{{"FirstAidKit",2},{"rhs_mag_rgd5",1,1}}},{"rhs_6b3_AK_3",{{"rhs_mag_30Rnd_556x45_M855A1_Stanag",10,30},{"rhs_mag_m67",2,1}}},{},"rhsusf_ach_bare_headset","rhs_scarf",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","rhs_1PN138"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'CTRG'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "CTRG";

    };

    class O_LibertyArmy_Rifleman_01 : O_LibertyArmy_Unarmed_01 {
        author = "VaD_3r";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman";
        side = 0;
        faction = "O_LibertyArmy";

        identityTypes[] = {"Head_Euro","LanguageRUS","rhs_scarf","G_CIVIL_male"};

        uniformClass = "rhs_uniform_FROG01_wd";

        linkedItems[] = {"rhsusf_spc_light","rhs_6b27m_green","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","rhs_1PN138"};
        respawnlinkedItems[] = {"rhsusf_spc_light","rhs_6b27m_green","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","rhs_1PN138"};

        weapons[] = {"rhs_weap_m4_carryhandle","Binocular"};
        respawnWeapons[] = {"rhs_weap_m4_carryhandle","Binocular"};

        magazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag","rhs_mag_30Rnd_556x45_M855A1_Stanag"};
        respawnMagazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag","rhs_mag_30Rnd_556x45_M855A1_Stanag"};

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_m4_carryhandle","","","rhsusf_acc_eotech_552",{"rhs_mag_30Rnd_556x45_M855A1_Stanag",30},{},""},{},{},{"rhs_uniform_FROG01_wd",{{"FirstAidKit",2},{"rhs_mag_rgd5",1,1},{"CUP_HandGrenade_M67",1,1}}},{"rhsusf_spc_light",{{"rhs_mag_30Rnd_556x45_M855A1_Stanag",10,30}}},{},"rhs_6b27m_green","rhsusf_shemagh2_gogg_tan",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","rhs_1PN138"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'CTRG'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "CTRG";

    };

    class O_LibertyArmy_Rifleman_AT_01 : O_LibertyArmy_Rifleman_01 {
        author = "VaD_3r";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman (AT)";
        side = 0;
        faction = "O_LibertyArmy";

        identityTypes[] = {"Head_Euro","LanguageRUS","rhs_scarf","G_CIVIL_male"};

        uniformClass = "rhs_uniform_FROG01_wd";

        linkedItems[] = {"rhsusf_spc_corpsman","H_Booniehat_khk_hs","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhsusf_spc_corpsman","H_Booniehat_khk_hs","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_m4a1_carryhandle","rhs_weap_maaws","Binocular"};
        respawnWeapons[] = {"rhs_weap_m4a1_carryhandle","rhs_weap_maaws","Binocular"};

        magazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag","rhs_mag_maaws_HEAT","rhs_mag_30Rnd_556x45_M855A1_Stanag"};
        respawnMagazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag","rhs_mag_maaws_HEAT","rhs_mag_30Rnd_556x45_M855A1_Stanag"};

        backpack = "rhsusf_assault_eagleaiii_coy";

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_m4a1_carryhandle","","rhs_acc_2dpZenit_ris","",{"rhs_mag_30Rnd_556x45_M855A1_Stanag",30},{},""},{"rhs_weap_maaws","","","rhs_optic_maaws",{"rhs_mag_maaws_HEAT",1},{},""},{},{"rhs_uniform_FROG01_wd",{{"FirstAidKit",2},{"rhs_mag_rgd5",1,1},{"CUP_HandGrenade_M67",1,1}}},{"rhsusf_spc_corpsman",{{"rhs_mag_30Rnd_556x45_M855A1_Stanag",10,30}}},{"rhsusf_assault_eagleaiii_coy",{{"rhs_mag_maaws_HEAT",1,1},{"rhs_mag_maaws_HE",2,1}}},"H_Booniehat_khk_hs","",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'CTRG'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "CTRG";

    };

    class O_LibertyArmy_Grenadier_01 : O_LibertyArmy_Unarmed_01 {
        author = "VaD_3r";
        scope = 2;
        scopeCurator = 2;
        displayName = "Grenadier";
        side = 0;
        faction = "O_LibertyArmy";

        identityTypes[] = {"Head_Euro","LanguageRUS","rhs_scarf","G_CIVIL_male"};

        uniformClass = "rhs_uniform_FROG01_wd";

        linkedItems[] = {"rhs_6b23_6sh116_vog","rhs_6b7_1m","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","rhs_1PN138"};
        respawnlinkedItems[] = {"rhs_6b23_6sh116_vog","rhs_6b7_1m","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","rhs_1PN138"};

        weapons[] = {"rhs_weap_m4_carryhandle_m203","Binocular"};
        respawnWeapons[] = {"rhs_weap_m4_carryhandle_m203","Binocular"};

        magazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag","rhs_mag_M441_HE","rhs_mag_30Rnd_556x45_M855A1_Stanag","rhs_mag_M441_HE"};
        respawnMagazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag","rhs_mag_M441_HE","rhs_mag_30Rnd_556x45_M855A1_Stanag","rhs_mag_M441_HE"};

        backpack = "B_AssaultPack_sgg";

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_m4_carryhandle_m203","","","",{"rhs_mag_30Rnd_556x45_M855A1_Stanag",30},{"rhs_mag_M441_HE",1},""},{},{},{"rhs_uniform_FROG01_wd",{{"FirstAidKit",2},{"rhs_mag_rgd5",1,1},{"rhs_mag_M441_HE",3,1}}},{"rhs_6b23_6sh116_vog",{{"rhs_mag_M441_HE",7,1},{"rhs_mag_30Rnd_556x45_M855A1_Stanag",9,30},{"rhs_mag_m662_red",2,1},{"CUP_1Rnd_SmokeYellow_M203",2,1},{"CUP_1Rnd_SmokeGreen_M203",1,1},{"CUP_1Rnd_SmokeRed_M203",2,1},{"CUP_1Rnd_Smoke_M203",2,1}}},{"B_AssaultPack_sgg",{{"rhs_mag_M441_HE",8,1}}},"rhs_6b7_1m","rhsusf_shemagh2_gogg_grn",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","rhs_1PN138"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'CTRG'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "CTRG";

    };

    class O_LibertyArmy_Specialist_01 : O_LibertyArmy_Unarmed_01 {
        author = "VaD_3r";
        scope = 2;
        scopeCurator = 2;
        displayName = "Specialist";
        side = 0;
        faction = "O_LibertyArmy";

        identityTypes[] = {"Head_Euro","LanguageRUS","rhs_scarf","G_CIVIL_male"};

        uniformClass = "rhs_uniform_FROG01_wd";

        linkedItems[] = {"rhsusf_plateframe_marksman","rhsusf_cvc_green_helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","rhsusf_ANPVS_15"};
        respawnlinkedItems[] = {"rhsusf_plateframe_marksman","rhsusf_cvc_green_helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","rhsusf_ANPVS_15"};

        weapons[] = {"CUP_arifle_HK417_12","Binocular"};
        respawnWeapons[] = {"CUP_arifle_HK417_12","Binocular"};

        magazines[] = {"CUP_20Rnd_762x51_HK417","CUP_20Rnd_762x51_HK417"};
        respawnMagazines[] = {"CUP_20Rnd_762x51_HK417","CUP_20Rnd_762x51_HK417"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_HK417_12","rhsusf_acc_aac_762sdn6_silencer","","rhsusf_acc_ACOG_USMC",{"CUP_20Rnd_762x51_HK417",20},{},"CUP_bipod_Harris_1A2_L_BLK"},{},{},{"rhs_uniform_FROG01_wd",{{"FirstAidKit",2},{"rhs_mag_rgd5",1,1},{"CUP_HandGrenade_M67",1,1}}},{"rhsusf_plateframe_marksman",{{"CUP_20Rnd_762x51_HK417",13,20}}},{},"rhsusf_cvc_green_helmet","G_Balaclava_combat",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","rhsusf_ANPVS_15"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'CTRG'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "CTRG";

    };

    class O_LibertyArmy_Machine_Gunner_01 : O_LibertyArmy_Unarmed_01 {
        author = "VaD_3r";
        scope = 2;
        scopeCurator = 2;
        displayName = "Machine Gunner";
        side = 0;
        faction = "O_LibertyArmy";

        identityTypes[] = {"Head_Euro","LanguageRUS","rhs_scarf","G_CIVIL_male"};

        uniformClass = "rhs_uniform_FROG01_wd";

        linkedItems[] = {"rhsusf_plateframe_machinegunner","H_Cap_blk","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhsusf_plateframe_machinegunner","H_Cap_blk","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"hlc_lmg_m60","Binocular"};
        respawnWeapons[] = {"hlc_lmg_m60","Binocular"};

        magazines[] = {"hlc_100Rnd_762x51_M_M60E4","hlc_100Rnd_762x51_M_M60E4"};
        respawnMagazines[] = {"hlc_100Rnd_762x51_M_M60E4","hlc_100Rnd_762x51_M_M60E4"};

        backpack = "B_AssaultPack_ocamo";

        ALiVE_orbatCreator_loadout[] = {{"hlc_lmg_m60","","","",{"hlc_100Rnd_762x51_M_M60E4",100},{},""},{},{},{"rhs_uniform_FROG01_wd",{{"FirstAidKit",1},{"rhs_mag_rgd5",1,1}}},{"rhsusf_plateframe_machinegunner",{{"hlc_100Rnd_762x51_M_M60E4",2,100}}},{"B_AssaultPack_ocamo",{{"hlc_100Rnd_762x51_M_M60E4",2,100}}},"H_Cap_blk","G_Combat",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'CTRG'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "CTRG";

    };

    class O_LibertyArmy_Machine_Gunner_Assistant_01 : O_LibertyArmy_Unarmed_01 {
        author = "VaD_3r";
        scope = 2;
        scopeCurator = 2;
        displayName = "Machine Gunner Assistant";
        side = 0;
        faction = "O_LibertyArmy";

        identityTypes[] = {"Head_Euro","LanguageRUS","rhs_scarf","G_CIVIL_male"};

        uniformClass = "rhs_uniform_FROG01_wd";

        linkedItems[] = {"rhs_6b5_ttsko","rhs_beanie_green","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhs_6b5_ttsko","rhs_beanie_green","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_m4_carryhandle","Binocular"};
        respawnWeapons[] = {"rhs_weap_m4_carryhandle","Binocular"};

        magazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag","rhs_mag_30Rnd_556x45_M855A1_Stanag"};
        respawnMagazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag","rhs_mag_30Rnd_556x45_M855A1_Stanag"};

        backpack = "B_AssaultPack_cbr";

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_m4_carryhandle","","","",{"rhs_mag_30Rnd_556x45_M855A1_Stanag",30},{},""},{},{},{"rhs_uniform_FROG01_wd",{{"FirstAidKit",2},{"rhs_mag_rgd5",1,1},{"rhs_mag_m67",1,1}}},{"rhs_6b5_ttsko",{{"rhs_mag_30Rnd_556x45_M855A1_Stanag",8,30}}},{"B_AssaultPack_cbr",{{"CUP_100Rnd_TE4_LRT4_Green_Tracer_762x51_Belt_M",3,100}}},"rhs_beanie_green","",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'CTRG'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "CTRG";

    };

    class O_LibertyArmy_Auto_Rifleman_01 : O_LibertyArmy_Unarmed_01 {
        author = "VaD_3r";
        scope = 2;
        scopeCurator = 2;
        displayName = "Auto Rifleman";
        side = 0;
        faction = "O_LibertyArmy";

        identityTypes[] = {"Head_Euro","LanguageRUS","rhs_scarf","G_CIVIL_male"};

        uniformClass = "rhs_uniform_FROG01_wd";

        linkedItems[] = {"rhs_6b23_6sh116_mixed","rhs_6b26_green","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","rhsusf_ANPVS_14"};
        respawnlinkedItems[] = {"rhs_6b23_6sh116_mixed","rhs_6b26_green","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","rhsusf_ANPVS_14"};

        weapons[] = {"rhs_weap_m249_pip_L_para","Binocular"};
        respawnWeapons[] = {"rhs_weap_m249_pip_L_para","Binocular"};

        magazines[] = {"rhsusf_200Rnd_556x45_box","rhsusf_200Rnd_556x45_box"};
        respawnMagazines[] = {"rhsusf_200Rnd_556x45_box","rhsusf_200Rnd_556x45_box"};

        backpack = "B_AssaultPack_sgg";

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_m249_pip_L_para","","rhsusf_acc_anpeq15side_bk","rhs_acc_rakursPM",{"rhsusf_200Rnd_556x45_box",200},{},"rhsusf_acc_saw_bipod"},{},{},{"rhs_uniform_FROG01_wd",{{"FirstAidKit",2},{"rhs_mag_rgd5",1,1}}},{"rhs_6b23_6sh116_mixed",{{"rhsusf_200Rnd_556x45_box",2,200}}},{"B_AssaultPack_sgg",{{"rhsusf_200Rnd_556x45_box",3,200}}},"rhs_6b26_green","rhsusf_oakley_goggles_blk",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","rhsusf_ANPVS_14"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'CTRG'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "CTRG";

    };

    class O_LibertyArmy_Sniper_01 : O_LibertyArmy_Unarmed_01 {
        author = "VaD_3r";
        scope = 2;
        scopeCurator = 2;
        displayName = "Sniper";
        side = 0;
        faction = "O_LibertyArmy";

        identityTypes[] = {"Head_Euro","LanguageRUS","rhs_scarf","G_CIVIL_male"};

        uniformClass = "rhs_uniform_FROG01_wd";

        linkedItems[] = {"rhs_6sh46","H_Cap_blk","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","rhsusf_ANPVS_14"};
        respawnlinkedItems[] = {"rhs_6sh46","H_Cap_blk","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","rhsusf_ANPVS_14"};

        weapons[] = {"CUP_srifle_M24_blk","rhsusf_weap_m1911a1","Binocular"};
        respawnWeapons[] = {"CUP_srifle_M24_blk","rhsusf_weap_m1911a1","Binocular"};

        magazines[] = {"CUP_5Rnd_762x51_M24","rhsusf_mag_7x45acp_MHP","CUP_5Rnd_762x51_M24","rhsusf_mag_7x45acp_MHP"};
        respawnMagazines[] = {"CUP_5Rnd_762x51_M24","rhsusf_mag_7x45acp_MHP","CUP_5Rnd_762x51_M24","rhsusf_mag_7x45acp_MHP"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_srifle_M24_blk","muzzle_snds_B","CUP_Mxx_camo_half","rhs_acc_dh520x56",{"CUP_5Rnd_762x51_M24",5},{},"rhs_acc_harris_swivel"},{},{"rhsusf_weap_m1911a1","","","",{"rhsusf_mag_7x45acp_MHP",7},{},""},{"rhs_uniform_FROG01_wd",{{"FirstAidKit",1},{"rhs_mag_rgd5",1,1},{"9Rnd_45ACP_Mag",4,9}}},{"rhs_6sh46",{{"rhsusf_5Rnd_762x51_m993_Mag",15,5}}},{},"H_Cap_blk","",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","rhsusf_ANPVS_14"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'CTRG'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "CTRG";

    };

};

//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 208.149102 on Stable branch
// Generated with ALiVE version 1.15.0.2112041
//////////////////////////////////////////////////////////////////////////////////

class CfgGroups {
    class EAST {

        class O_LibertyArmy {
            name = "Livonia STALKER : Liberty";

            class Infantry {
                name = "Infantry";

                class o_libertyarmy_infantry_team {
                    name = "Team";
                    side = 0;
                    faction = "O_LibertyArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_LibertyArmy_Team_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_LibertyArmy_Squad_Leader_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_LibertyArmy_Specialist_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_LibertyArmy_Sniper_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_LibertyArmy_Grenadier_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_LibertyArmy_Machine_Gunner_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_LibertyArmy_Machine_Gunner_Assistant_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_LibertyArmy_Auto_Rifleman_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_LibertyArmy_Rifleman_AT_01";
                    };
                    class Unit9 {
                        position[] = {25,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_LibertyArmy_Rifleman_01";
                    };
                };

                class o_libertyarmy_infantry_squad {
                    name = "Squad";
                    side = 0;
                    faction = "O_LibertyArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_LibertyArmy_Squad_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_LibertyArmy_Specialist_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_LibertyArmy_Grenadier_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_LibertyArmy_Sniper_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_LibertyArmy_Machine_Gunner_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_LibertyArmy_Machine_Gunner_Assistant_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_LibertyArmy_Auto_Rifleman_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_LibertyArmy_Rifleman_AT_01";
                    };
                    class Unit8 {
                        position[] = {-20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_LibertyArmy_Rifleman_01";
                    };
                };

                class o_libertyarmy_infantry_recon {
                    name = "Recon";
                    side = 0;
                    faction = "O_LibertyArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_LibertyArmy_Team_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_LibertyArmy_Specialist_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_LibertyArmy_Sniper_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_LibertyArmy_Auto_Rifleman_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_LibertyArmy_Rifleman_AT_01";
                    };
                };

                class o_libertyarmy_infantry_patrol {
                    name = "Patrol";
                    side = 0;
                    faction = "O_LibertyArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_LibertyArmy_Squad_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_LibertyArmy_Grenadier_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_LibertyArmy_Machine_Gunner_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_LibertyArmy_Rifleman_01";
                    };
                };

                class o_libertyarmy_infantry_special {
                    name = "Special";
                    side = 0;
                    faction = "O_LibertyArmy";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_LibertyArmy_Squad_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_LibertyArmy_Specialist_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_LibertyArmy_Grenadier_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_LibertyArmy_Sniper_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_LibertyArmy_Rifleman_AT_01";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

            };

            class Motorized {
                name = "Motorized Infantry";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

            };

            class Armored {
                name = "Armor";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};