//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 208.149102 on Stable branch
// Generated with ALiVE version 1.15.0.2112041
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class I_MercenariesMercenaries {
        displayName = "Livonia STALKER : White Lake Mercenaries";
        side = 2;
        flag = "\a3\UI_F_Enoch\Data\CfgMarkers\Astra_CA.paa";
        icon = "\a3\UI_F_Enoch\Data\CfgMarkers\Astra_CA.paa";
        priority = 0;
    };
};

//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 208.149102 on Stable branch
// Generated with ALiVE version 1.15.0.2112041
//////////////////////////////////////////////////////////////////////////////////


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class I_G_Soldier_F;
    class I_G_Soldier_F_OCimport_01 : I_G_Soldier_F { scope = 0; class EventHandlers; };
    class I_G_Soldier_F_OCimport_02 : I_G_Soldier_F_OCimport_01 { class EventHandlers; };


    class I_IMercenariesMercenaries_Unarmed_01 : I_G_Soldier_F_OCimport_02 {
        author = "Dima";
        scope = 2;
        scopeCurator = 2;
        displayName = "Unarmed";
        side = 2;
        faction = "I_MercenariesMercenaries";

        identityTypes[] = {"Head_NATO","LanguageGRE_F","G_GUERIL_default"};

        uniformClass = "rhs_uniform_gorka_r_g_gloves";

        linkedItems[] = {"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","rhsusf_ANPVS_15"};
        respawnlinkedItems[] = {"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","rhsusf_ANPVS_15"};

        weapons[] = {"Binocular"};
        respawnWeapons[] = {"Binocular"};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"rhs_uniform_gorka_r_g_gloves",{{"FirstAidKit",1},{"MiniGrenade",1,1}}},{},{},"","",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","rhsusf_ANPVS_15"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'Astra'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "Astra";

    };

    class I_IMercenariesMercenaries_Leader_01 : I_IMercenariesMercenaries_Unarmed_01 {
        author = "Dima";
        scope = 2;
        scopeCurator = 2;
        displayName = "Leader";
        side = 2;
        faction = "I_MercenariesMercenaries";

        identityTypes[] = {"Head_NATO","LanguageGRE_F","G_GUERIL_default"};

        uniformClass = "rhs_uniform_gorka_r_g_gloves";

        linkedItems[] = {"rhsgref_6b23_khaki_rifleman","rhsusf_opscore_mar_fg_pelt","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","rhsusf_ANPVS_15"};
        respawnlinkedItems[] = {"rhsgref_6b23_khaki_rifleman","rhsusf_opscore_mar_fg_pelt","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","rhsusf_ANPVS_15"};

        weapons[] = {"CUP_arifle_ACR_blk_556","Binocular"};
        respawnWeapons[] = {"CUP_arifle_ACR_blk_556","Binocular"};

        magazines[] = {"CUP_30Rnd_556x45_Stanag","CUP_30Rnd_556x45_Stanag"};
        respawnMagazines[] = {"CUP_30Rnd_556x45_Stanag","CUP_30Rnd_556x45_Stanag"};

        ALiVE_orbatCreator_loadout[] = {{"CUP_arifle_ACR_blk_556","rhsusf_acc_nt4_black","rhsusf_acc_anpeq15side_bk","rhsusf_acc_ACOG2_USMC",{"CUP_30Rnd_556x45_Stanag",30},{},""},{},{},{"rhs_uniform_gorka_r_g_gloves",{{"FirstAidKit",2},{"MiniGrenade",1,1},{"HandGrenade",1,1}}},{"rhsgref_6b23_khaki_rifleman",{{"CUP_30Rnd_556x45_Stanag",10,30},{"HandGrenade",2,1}}},{},"rhsusf_opscore_mar_fg_pelt","rhsusf_shemagh2_grn",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","rhsusf_ANPVS_15"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'Astra'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "Astra";

    };

    class I_IMercenariesMercenaries_Rifleman_01 : I_IMercenariesMercenaries_Unarmed_01 {
        author = "Dima";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman";
        side = 2;
        faction = "I_MercenariesMercenaries";

        identityTypes[] = {"Head_NATO","LanguageGRE_F","G_GUERIL_default"};

        uniformClass = "rhs_uniform_gorka_r_g_gloves";

        linkedItems[] = {"rhsusf_mbav_rifleman","rhsusf_cvc_green_alt_helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","rhsusf_ANPVS_15"};
        respawnlinkedItems[] = {"rhsusf_mbav_rifleman","rhsusf_cvc_green_alt_helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","rhsusf_ANPVS_15"};

        weapons[] = {"rhs_weap_m4a1_blockII","Binocular"};
        respawnWeapons[] = {"rhs_weap_m4a1_blockII","Binocular"};

        magazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag","rhs_mag_30Rnd_556x45_M855A1_Stanag"};
        respawnMagazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag","rhs_mag_30Rnd_556x45_M855A1_Stanag"};

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_m4a1_blockII","rhsusf_acc_nt4_black","rhsusf_acc_anpeq15side_bk","optic_Arco_blk_F",{"rhs_mag_30Rnd_556x45_M855A1_Stanag",30},{},"rhsusf_acc_grip2"},{},{},{"rhs_uniform_gorka_r_g_gloves",{{"FirstAidKit",2},{"MiniGrenade",1,1},{"HandGrenade",1,1}}},{"rhsusf_mbav_rifleman",{{"rhs_mag_30Rnd_556x45_M855A1_Stanag",10,30},{"HandGrenade",3,1}}},{},"rhsusf_cvc_green_alt_helmet","rhsusf_shemagh2_gogg_tan",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","rhsusf_ANPVS_15"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'Astra'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "Astra";

    };

    class I_IMercenariesMercenaries_Specialist_01 : I_IMercenariesMercenaries_Unarmed_01 {
        author = "Dima";
        scope = 2;
        scopeCurator = 2;
        displayName = "Specialist";
        side = 2;
        faction = "I_MercenariesMercenaries";

        identityTypes[] = {"Head_NATO","LanguageGRE_F","G_GUERIL_default"};

        uniformClass = "rhs_uniform_gorka_r_g_gloves";

        linkedItems[] = {"rhsusf_iotv_ocp_Rifleman","rhs_beanie_green","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","CUP_NVG_PVS15_black"};
        respawnlinkedItems[] = {"rhsusf_iotv_ocp_Rifleman","rhs_beanie_green","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","CUP_NVG_PVS15_black"};

        weapons[] = {"rhs_weap_m14ebrri","rhsusf_weap_m9","Binocular"};
        respawnWeapons[] = {"rhs_weap_m14ebrri","rhsusf_weap_m9","Binocular"};

        magazines[] = {"rhsusf_20Rnd_762x51_m118_special_Mag","rhsusf_mag_15Rnd_9x19_JHP","rhsusf_20Rnd_762x51_m118_special_Mag","rhsusf_mag_15Rnd_9x19_JHP"};
        respawnMagazines[] = {"rhsusf_20Rnd_762x51_m118_special_Mag","rhsusf_mag_15Rnd_9x19_JHP","rhsusf_20Rnd_762x51_m118_special_Mag","rhsusf_mag_15Rnd_9x19_JHP"};

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_m14ebrri","rhsusf_acc_aac_762sd_silencer","rhsusf_acc_anpeq15side_bk","rhsusf_acc_su230",{"rhsusf_20Rnd_762x51_m118_special_Mag",20},{},"rhsusf_acc_harris_bipod"},{},{"rhsusf_weap_m9","","","",{"rhsusf_mag_15Rnd_9x19_JHP",15},{},""},{"rhs_uniform_gorka_r_g_gloves",{{"FirstAidKit",2},{"MiniGrenade",1,1},{"rhsusf_mag_15Rnd_9x19_JHP",3,15}}},{"rhsusf_iotv_ocp_Rifleman",{{"rhsusf_20Rnd_762x51_m993_Mag",8,20}}},{},"rhs_beanie_green","G_Bandanna_oli",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","CUP_NVG_PVS15_black"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'Astra'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "Astra";

    };

    class I_IMercenariesMercenaries_Auto_Rifleman_01 : I_IMercenariesMercenaries_Unarmed_01 {
        author = "Dima";
        scope = 2;
        scopeCurator = 2;
        displayName = "Auto Rifleman";
        side = 2;
        faction = "I_MercenariesMercenaries";

        identityTypes[] = {"Head_NATO","LanguageGRE_F","G_GUERIL_default"};

        uniformClass = "rhs_uniform_gorka_r_g_gloves";

        linkedItems[] = {"rhsusf_spcs_ucp_machinegunner","rhsusf_opscore_rg_cover_pelt","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","rhsusf_ANPVS_15"};
        respawnlinkedItems[] = {"rhsusf_spcs_ucp_machinegunner","rhsusf_opscore_rg_cover_pelt","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","rhsusf_ANPVS_15"};

        weapons[] = {"hlc_lmg_minimipara_long_railed","Binocular"};
        respawnWeapons[] = {"hlc_lmg_minimipara_long_railed","Binocular"};

        magazines[] = {"hlc_200rnd_556x45_M_SAW","hlc_200rnd_556x45_M_SAW"};
        respawnMagazines[] = {"hlc_200rnd_556x45_M_SAW","hlc_200rnd_556x45_M_SAW"};

        backpack = "rhsusf_assault_eagleaiii_ucp";

        ALiVE_orbatCreator_loadout[] = {{"hlc_lmg_minimipara_long_railed","rhsusf_acc_nt4_black","","rhsusf_acc_g33_xps3",{"hlc_200rnd_556x45_M_SAW",200},{},""},{},{},{"rhs_uniform_gorka_r_g_gloves",{{"FirstAidKit",1},{"MiniGrenade",1,1}}},{"rhsusf_spcs_ucp_machinegunner",{{"hlc_200rnd_556x45_M_SAW",2,200}}},{"rhsusf_assault_eagleaiii_ucp",{{"hlc_200rnd_556x45_M_SAW",2,200}}},"rhsusf_opscore_rg_cover_pelt","G_Balaclava_TI_G_blk_F",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","rhsusf_ANPVS_15"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'Astra'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "Astra";

    };

    class I_IMercenariesMercenaries_Sniper_01 : I_IMercenariesMercenaries_Unarmed_01 {
        author = "Dima";
        scope = 2;
        scopeCurator = 2;
        displayName = "Sniper";
        side = 2;
        faction = "I_MercenariesMercenaries";

        identityTypes[] = {"Head_NATO","LanguageGRE_F","G_GUERIL_default"};

        uniformClass = "rhs_uniform_gorka_r_g_gloves";

        linkedItems[] = {"rhs_6b45_light","H_Booniehat_khk_hs","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","CUP_NVG_PVS15_black"};
        respawnlinkedItems[] = {"rhs_6b45_light","H_Booniehat_khk_hs","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","CUP_NVG_PVS15_black"};

        weapons[] = {"rhs_weap_m40a5","CUP_hgun_M17_Black","Binocular"};
        respawnWeapons[] = {"rhs_weap_m40a5","CUP_hgun_M17_Black","Binocular"};

        magazines[] = {"rhsusf_5Rnd_762x51_AICS_m118_special_Mag","CUP_21Rnd_9x19_M17_Black","rhsusf_5Rnd_762x51_AICS_m118_special_Mag","CUP_21Rnd_9x19_M17_Black"};
        respawnMagazines[] = {"rhsusf_5Rnd_762x51_AICS_m118_special_Mag","CUP_21Rnd_9x19_M17_Black","rhsusf_5Rnd_762x51_AICS_m118_special_Mag","CUP_21Rnd_9x19_M17_Black"};

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_m40a5","","rhsusf_acc_anpeq15side","rhsusf_acc_nxs_3515x50_md",{"rhsusf_5Rnd_762x51_AICS_m118_special_Mag",5},{},"rhsusf_acc_harris_swivel"},{},{"CUP_hgun_M17_Black","","","",{"CUP_21Rnd_9x19_M17_Black",21},{},""},{"rhs_uniform_gorka_r_g_gloves",{{"FirstAidKit",1},{"MiniGrenade",1,1},{"CUP_21Rnd_9x19_M17_Black",3,21}}},{"rhs_6b45_light",{{"FirstAidKit",1},{"rhsusf_5Rnd_762x51_AICS_m993_Mag",15,5},{"CUP_21Rnd_9x19_M17_Black",1,21}}},{},"H_Booniehat_khk_hs","rhsusf_shemagh2_grn",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","CUP_NVG_PVS15_black"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'Astra'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "Astra";

    };

    class I_IMercenariesMercenaries_WLM_Conscript_AKM_01 : I_IMercenariesMercenaries_Unarmed_01 {
        author = "Dima";
        scope = 2;
        scopeCurator = 2;
        displayName = "WLM Conscript (AKM)";
        side = 2;
        faction = "I_MercenariesMercenaries";

        identityTypes[] = {"Head_Euro","LanguageGRE_F","G_GUERIL_default"};

        uniformClass = "rhsgref_uniform_woodland_olive";

        linkedItems[] = {"rhsusf_iotv_ocp_Rifleman","H_Watchcap_blk","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhsusf_iotv_ocp_Rifleman","H_Watchcap_blk","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_akm","Binocular"};
        respawnWeapons[] = {"rhs_weap_akm","Binocular"};

        magazines[] = {"rhs_30Rnd_762x39mm_bakelite","rhs_30Rnd_762x39mm_bakelite"};
        respawnMagazines[] = {"rhs_30Rnd_762x39mm_bakelite","rhs_30Rnd_762x39mm_bakelite"};

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_akm","rhs_acc_pbs1","","",{"rhs_30Rnd_762x39mm_bakelite",30},{},""},{},{},{"rhsgref_uniform_woodland_olive",{{"FirstAidKit",2},{"MiniGrenade",1,1}}},{"rhsusf_iotv_ocp_Rifleman",{{"rhs_30Rnd_762x39mm_bakelite",10,30}}},{},"H_Watchcap_blk","",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'Astra'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "Astra";

    };

    class I_IMercenariesMercenaries_WLM_Conscript_M4_01 : I_IMercenariesMercenaries_WLM_Conscript_AKM_01 {
        author = "Dima";
        scope = 2;
        scopeCurator = 2;
        displayName = "WLM Conscript (M4)";
        side = 2;
        faction = "I_MercenariesMercenaries";

        identityTypes[] = {"Head_Euro","LanguageGRE_F","G_GUERIL_default"};

        uniformClass = "rhsgref_uniform_tigerstripe";

        linkedItems[] = {"rhsusf_iotv_ocp_Rifleman","H_Cap_grn","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhsusf_iotv_ocp_Rifleman","H_Cap_grn","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_m4","Binocular"};
        respawnWeapons[] = {"rhs_weap_m4","Binocular"};

        magazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag","rhs_mag_30Rnd_556x45_M855A1_Stanag"};
        respawnMagazines[] = {"rhs_mag_30Rnd_556x45_M855A1_Stanag","rhs_mag_30Rnd_556x45_M855A1_Stanag"};

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_m4","hlc_muzzle_556NATO_M42000","","",{"rhs_mag_30Rnd_556x45_M855A1_Stanag",30},{},""},{},{},{"rhsgref_uniform_tigerstripe",{{"FirstAidKit",2},{"rhs_mag_30Rnd_556x45_M855A1_Stanag",2,30}}},{"rhsusf_iotv_ocp_Rifleman",{{"rhs_mag_30Rnd_556x45_M855A1_Stanag",10,30}}},{},"H_Cap_grn","G_Shades_Blue",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'Astra'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "Astra";

    };

    class I_IMercenariesMercenaries_WLM_Conscript_M14_01 : I_IMercenariesMercenaries_WLM_Conscript_M4_01 {
        author = "Dima";
        scope = 2;
        scopeCurator = 2;
        displayName = "WLM Conscript (M14)";
        side = 2;
        faction = "I_MercenariesMercenaries";

        identityTypes[] = {"Head_Euro","LanguageGRE_F","G_GUERIL_default"};

        uniformClass = "rhsgref_uniform_tigerstripe";

        linkedItems[] = {"rhsusf_mbav_rifleman","rhs_6b26_bala_green","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhsusf_mbav_rifleman","rhs_6b26_bala_green","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_m14_rail","Binocular"};
        respawnWeapons[] = {"rhs_weap_m14_rail","Binocular"};

        magazines[] = {"rhsusf_20Rnd_762x51_m80_Mag","rhsusf_20Rnd_762x51_m80_Mag"};
        respawnMagazines[] = {"rhsusf_20Rnd_762x51_m80_Mag","rhsusf_20Rnd_762x51_m80_Mag"};

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_m14_rail","rhsgref_sdn6_suppressor","","rhsusf_acc_ACOG2_USMC",{"rhsusf_20Rnd_762x51_m80_Mag",20},{},"rhsusf_acc_m14_bipod"},{},{},{"rhsgref_uniform_tigerstripe",{{"FirstAidKit",2},{"rhsusf_20Rnd_762x51_m80_Mag",1,20}}},{"rhsusf_mbav_rifleman",{{"rhsusf_20Rnd_762x51_m80_Mag",8,20}}},{},"rhs_6b26_bala_green","G_Sport_Blackyellow",{"Binocular","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;[_this, 'Astra'] call BIS_fnc_setUnitInsignia;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_insignia = "Astra";

    };

};

//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 208.149102 on Stable branch
// Generated with ALiVE version 1.15.0.2112041
//////////////////////////////////////////////////////////////////////////////////

class CfgGroups {
    class Indep {

        class I_MercenariesMercenaries {
            name = "Livonia STALKER : White Lake Mercenaries";

            class Infantry {
                name = "Infantry";

                class i_imercenariesmercenaries_infantry_team {
                    name = "Team";
                    side = 2;
                    faction = "I_MercenariesMercenaries";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_IMercenariesMercenaries_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_IMercenariesMercenaries_Specialist_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_IMercenariesMercenaries_Sniper_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_IMercenariesMercenaries_Auto_Rifleman_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_IMercenariesMercenaries_Rifleman_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_IMercenariesMercenaries_WLM_Conscript_AKM_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_IMercenariesMercenaries_WLM_Conscript_M4_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_IMercenariesMercenaries_WLM_Conscript_M14_01";
                    };
                };

                class i_imercenariesmercenaries_infantry_squad {
                    name = "Squad";
                    side = 2;
                    faction = "I_MercenariesMercenaries";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_IMercenariesMercenaries_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_IMercenariesMercenaries_Specialist_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_IMercenariesMercenaries_Sniper_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_IMercenariesMercenaries_Auto_Rifleman_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_IMercenariesMercenaries_Rifleman_01";
                    };
                };

                class i_imercenariesmercenaries_infantry_recon {
                    name = "Recon";
                    side = 2;
                    faction = "I_MercenariesMercenaries";
                    icon = "\A3\ui_f\data\map\markers\nato\n_recon.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_IMercenariesMercenaries_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_IMercenariesMercenaries_Specialist_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_IMercenariesMercenaries_Sniper_01";
                    };
                };

                class i_imercenariesmercenaries_infantry_patrol {
                    name = "Patrol";
                    side = 2;
                    faction = "I_MercenariesMercenaries";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_IMercenariesMercenaries_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_IMercenariesMercenaries_Specialist_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_IMercenariesMercenaries_Auto_Rifleman_01";
                    };
                };

                class i_imercenariesmercenaries_infantry_special {
                    name = "Special";
                    side = 2;
                    faction = "I_MercenariesMercenaries";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_IMercenariesMercenaries_Leader_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_IMercenariesMercenaries_Specialist_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_IMercenariesMercenaries_Sniper_01";
                    };
                };

                class i_imercenariesmercenaries_infantry_conscripts {
                    name = "Conscripts";
                    side = 2;
                    faction = "I_MercenariesMercenaries";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "I_IMercenariesMercenaries_WLM_Conscript_AKM_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_IMercenariesMercenaries_WLM_Conscript_M4_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_IMercenariesMercenaries_WLM_Conscript_M14_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_IMercenariesMercenaries_WLM_Conscript_AKM_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_IMercenariesMercenaries_WLM_Conscript_M4_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "I_IMercenariesMercenaries_WLM_Conscript_M14_01";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

            };

            class Motorized {
                name = "Motorized Infantry";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

            };

            class Armored {
                name = "Armor";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};